# Generated by Django 3.2.13 on 2022-05-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_sub_total_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='sub_total',
        ),
    ]
