# Generated by Django 3.2.13 on 2022-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220510_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_qty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
