# Generated by Django 3.2.13 on 2022-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_qty',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
